sudo: false
language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email:
    on_failure: change
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@^3.0.0
  - npm install
before_script:
  - npm prune
  - export DISPLAY=:99.0
script:
  - npm run build
